name: Manage Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - packages/action-label-manager/**
  workflow_dispatch:

concurrency: manage-labels

jobs:
  manage-labels:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: oliversalzburg/action-label-manager@v0.0.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
