name: Manage Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - packages/action-label-manager/**
  workflow_dispatch:

concurrency: manage-labels

jobs:
  manage-labels:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          # renovate: datasource=docker depName=node versioning=node
          node-version: "20.12.2"
      - run: yarn install --immutable
      - run: yarn build:all

      - uses: ./packages/action-label-manager
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
