name: Update Schemas and Presets

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/schema-update.yml"
      - "packages/action-schema-update/*"
  workflow_dispatch:

concurrency: schema-update

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::022327457572:role/ks-website-maintainer
          role-session-name: GitHubActions

      - name: Deploy to S3
        run: |
          aws s3 sync ./schemas/working-draft s3://kitten-science-website/schemas/working-draft --delete
          aws s3 sync ./baselines s3://kitten-science-website/baselines --delete
          aws s3 sync ./presets s3://kitten-science-website/presets --delete
